### ISSUE TITLE
DAAL package renaming and question on additional packages

### ISSUE THREAD

**Issue by napetrov** [conda-forge/intel_repack-feedstock#16]
This is more a discussion and heads-up

- DAAL product have been renamed to oneDAL and we also changing conda package name to dal. There are couple ways how this can be implemented in repack recipe.

1  Just rename package to dal. Existing users of daal package have to update their recipes in order to migrate
2  Provide dummy daal packages that will require corresponding dal packages. In this case there will be more transparent migration process

For conda-forge i'm more leaning to first option.

and also question on adding additional package to repack? Is this feasible?

1. Intel mpi. it will be good to have this alternative to mpich avaialbe. Also there is no working analog for this on windows, so our distributed support in daal4py package is disabled on windows now
2. dpcpp_rt package - runtime for DPCPP compiler
3. New packages - particularly oneCCL. This is another communication library that have GPU support and will be required for daal4py to provide multiGPU support.  I think this also will be usefull for some other packages to have such tool in conda-forge

**Comment by napetrov** [comment]
@beckermr  @isuruf  - appreciate your comments here

**Comment by beckermr** [comment]
It might be good to have a more coherent discussion about how exactly we want conda-forge to interact with intel products and packages. Adding in packages for the other intel components, like intel mpi is in principle a good idea. However, we should figure out what parts of the conda-forge stack it makes sense to build with them, especially the oneAPI compilers.

On the issue of dal vs daal, my preference is item 2 above to help users transition.

**Comment by isuruf** [comment]
@napetrov, is the intel mpich 2021 ABI compatible with mpich? https://wiki.mpich.org/mpich/index.php/ABI_Compatibility_Initiative seems to be an old document.

Also, I'd like to see `opencl_rt` added as well. Would it be possible to add it as well? I see https://anaconda.org/intel/opencl_rt/  (we might have to change the name to `intel_opencl_rt` to avoid confusion)

**Comment by isuruf** [comment]
>  Also there is no working analog for this on windows, so our distributed support in daal4py package is disabled on windows now

We have msmpi packaged for windows. Maybe you can use it

**Comment by napetrov** [comment]
@beckermr  - yes, probably it require discussion. I think @tomashek  will be interested in this discusison as well.
 ok, will prepare second option for daal dal renaming

@isuruf  -  on ABI compatibility i think @ykiryano can help with answer. 
But in general does this even required?  Package will have opportunity to select ether of mpich or impi depending on their preference - it impi will be available in conda-forge as well, there shouldn't be an issue. Or i'm missing some point here?

on opencl_rt - i think this should be covered as part of overall discussion on getting Intel packages in conda-forge. But i don't see problems associated with this.

I've try msmpi - it dosn't work as in-place replacement, i guess there is way to enable it, but i think there is more sense to just get impi. daal4py designed to work with it

**Comment by isuruf** [comment]
>  But in general does this even required? Package will have opportunity to select ether of mpich or impi depending on their preference - it impi will be available in conda-forge as well, there shouldn't be an issue. Or i'm missing some point here?

If they are ABI compatible, it would simply mean that we can build packages with mpich and simply replace the mpich requirement with impi with the same package. Then we don't have to build packages with `impi`. This will look similar to what debian does with `update-alternatives` mechanism.
This is what we do with `BLAS`. We don't build with MKL except where packages uses API other than standard BLAS API, but swap the implementation since MKL and other blas implementations have the same ABI (when gfortran ABI of MKL is selected).
See https://conda-forge.org/docs/maintainer/knowledge_base.html#switching-blas-implementation

**Comment by napetrov** [comment]
@isuruf  @beckermr  we are working on getting green light for following packages
oneDNN
IPP
MPI
oneCCL
DPCPP RT
+ compilers

I would discuss more technical side on how this can be achieved.

I'm afraid with additional of  5+ new packages this recipe will be quite messy and we also have no validation of packages after repack.

I think in the past we were discussion option for direct packages cloning from Intel channels  as this would be easier to maintain and also we can guarantee packages validation. 

Appreciate you thoughts and comments here.

**Comment by beckermr** [comment]
Yes. We should discuss this again at a core meeting. I got an email from Andres Guzman-Ballen (who is at intel in austin, tx according to the note) on the ICC compiler packages. It would be good to make sure everyone is on the same page.

**Comment by isuruf** [comment]
For open source packages, we are going to require building from source as binary repackaging is reserved for proprietary software and in rare cases such as when the build takes >6 hours.

**Comment by napetrov** [comment]
@isuruf  - yes, it's clear that build option is preferred. But now i'm talking about proprietary packages only
