### ISSUE TITLE
Introducing  dpcpp_cpp_rt to repack

### ISSUE THREAD

**Issue by napetrov** [conda-forge/intel_repack-feedstock#22]
Hi,
we have new version of dpcpp_cpp_rt package uploaded to intel channel -  linux-64/dpcpp_cpp_rt-2021.2.0-intel_610.tar.bz2 

now package contains credist file that lists content and allows redistribution according to license. @beckermr @isuruf  - any objections for enabling it in repack?

**Comment by isuruf** [comment]
It is still licensed under "Intel End User License Agreement for Developer Tools", right?

**Comment by napetrov** [comment]
@isuruf  yes, correct.
