### ISSUE TITLE
Possible calling convention issues around registers with AVX512

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/intel_repack-feedstock#28]
Hello @conda-forge/intel_repack  @sknepper

we're hitting some problems in https://github.com/conda-forge/numpy-feedstock/pull/238 about registers on AVX512 with MKL. One question that came up is:
> @mattip:  Is there a way to discover which compiler built the MKL package?

Would you be able to answer this for us, please?

<details>
<summary>More context:</summary>

> @mattip: The JIT writes out assembly code and needs to carefully restore some registers when returning from a call. It seems there are discrepancies between [this wikipedia article](https://en.wikipedia.org/wiki/X86_calling_conventions#Microsoft_x64_calling_convention) and this [microsoft article](https://docs.microsoft.com/en-us/cpp/build/x64-calling-convention?view=msvc-160#callercallee-saved-registers) about which registers are considered non-volatile. In the code [PyPy considers these](https://foss.heptapod.net/pypy/pypy/-/blob/release-pypy2.7-v7.3.5/rpython/jit/backend/x86/runner.py#L160) which I think comes from wikipedia so 🤷? I am trying to get access to a AVX512 machine to test yet another wild theory.

[...]

> @mattip: Could we try to require openblas instead of mkl? Maybe there are some latent bugs in mkl on windows that pypy is exposing

> @h-vetinari: We can try using openblas in CI here, but MKL will still be the default on windows, so we wouldn't really be changing anything.
> [...]
> Regarding MKL, we can try if their most recent version fixes the issue as soon as [conda-forge/blas-feedstock#74](https://github.com/conda-forge/blas-feedstock/pull/74) is merged (we could pull this forward - blis & MKL are ready - otherwise we're waiting for some openblas issues around the 0.3.16 release to be resolved first).

> @mattip: I don't see anything in the [mkl 2021.3 bugfixes](https://software.intel.com/content/www/us/en/develop/articles/intel-oneapi-math-kernel-library-onemkl-bug-fixes.html) that catches my eye. I ask about mkl because when I build locally on a avx512-enbled machine with openblas I do not get a segfault, when I build via the recipe I do get a segfault. Although now that I can reproduce the segfault, perhaps I can try to instrument the code to find exactly where the full_args struct is getting zeroed out.
>
> Is there a way to discover which compiler built the MKL package?

</details>

**Comment by mattip** [comment]
Just to sharpen the question a bit: Apparently there was a [bugfix in Nov2020](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#-visual-studio-2017-version-15929) around movaps for unaligned assignments on x64. Is the current MKL package 2021.2 built with a compiler that contains this bugfix, and might it be relevant?

**Comment by isuruf** [comment]
> Is the current MKL package 2021.2 built with a compiler that contains this bugfix, and might it be relevant?

It's probably Intel compiler, so bugfixes in MSVC doesn't matter.

**Comment by mattip** [comment]
The root cause of the PyPy crashes this time was a PyPy JIT bug on windows64
xref https://foss.heptapod.net/pypy/pypy/-/merge_requests/829

**Comment by h-vetinari** [comment]
Given the updated information, I think it's OK to close this issue. If someone wants to chime in what compiler was used, that would still be much appreciated!

**Comment by napetrov** [comment]
MKL bits are build with Intel compiler. But the tricky part is that ICC have dependency on vc - we will post some answer from ICC team on affects from problem linked above
