### ISSUE TITLE
Intel MPI

### ISSUE THREAD

**Issue by dalcinl** [conda-forge/intel_repack-feedstock#48]
### Comment:

Would it be possible to add support for Intel MPI to this feedstock? I'm particularly interested in having Intel MPI as a choice for Windows users. Currently, the only MPI implementation available in Windows is Microsoft MPI, and it is a bit dated (MPI-2.0 officially, although all of MPI-2.2 functions are available).  

IMHO, at this points MSMPI looks a bit like abandonware, and the maintainers at the GitHub repo are unresponsive to requests.  Don't you agree, @isuruf? On the contrary, Intel MPI still gets regular updates, it supports the MPI 3.1 standard, and passes most of the mpi4py testsuite.

**Comment by isuruf** [comment]
Yes, Intel MPI would be good to have. We would need help from someone at Intel to create a conda package for it so that we can repackage it here and also permission to repackage.

**Comment by dalcinl** [comment]
Well, the conda packages already exist, they are available in the `intel` channel, with names `impi_rt` and `impi-devel`. I'm not sure how we could take advantages of them for the conda-forge repackage.

**Comment by napetrov** [comment]
Runtime package can be for sure repackaged, and as for dev package - will check license there in terms of redistribution.

**Comment by dalcinl** [comment]
@napetrov  Both the runtime (`impi_rt`) and development (`impi-devel`) packages are listed with `License: Intel Simplified Software License` in the anaconda.org/intel . IANAL, but looks that we are good.

**Comment by napetrov** [comment]
@dalcinl  - things are a bit more complex. ISSL allows use but not redistribution. And i've also checked impi_rt - there is no redist file there, so non of binaries there are "technically" allowed for redistribution. 

Will start discussion on this within Intel, but from high level perspective
1. I think that not having redist file in impi_rt is bug and not a feature - so would be fairly easy(next release) to fix if this is true.
2. On dev - this would require discussion and i'm not sure where or when we would endup

**Comment by napetrov** [comment]
@dalcinl - writing new comment to trigger notification. there is no license restriction and package can be added

**Comment by dalcinl** [comment]
I have no idea how to actually update this feedstock. There are multiple sources for the binaries: Intel's anaconda.org channel, NuGet, and downloadable offline installers.

**Comment by napetrov** [comment]
@dalcinl  - https://github.com/conda-forge/intel_repack-feedstock/pull/49
This should work for now. As alternative solution if you would like more control impi repack can be put in separate feedstock
