### ISSUE TITLE
Support for Lapack 3.9

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/intel_repack-feedstock#6]
Last [info](https://github.com/conda-forge/intel_repack-feedstock/pull/5#issuecomment-619981514) was (2020/04/27):

> @oleksandr-pavlyk: According to https://software.intel.com/en-us/forums/intel-math-kernel-library/topic/840653 MKL supports Lapack 3.8.0 API.
>
> I will ask around for the upgrade timeline.

Opening an issue to track this, as it blocks (to a degree; notwithstanding the `track_features` [approach](https://github.com/conda-forge/lapack-feedstock/pull/32#issuecomment-620678011)) both https://github.com/conda-forge/lapack-feedstock/pull/32 and https://github.com/conda-forge/blas-feedstock/pull/43.

**Comment by h-vetinari** [comment]
@oleksandr-pavlyk 
Any update on a timeline for lapack 3.9? :)

**Comment by oleksandr-pavlyk** [comment]
> Any update on a timeline for lapack 3.9? :)

The support is coming for no sooner than MKL 2020 update 3.

**Comment by h-vetinari** [comment]
OK, thanks for the update! 🙂 
Update 3 sounds like 2020'Q3? Or is there an ETA?

**Comment by h-vetinari** [comment]
Ping @oleksandr-pavlyk on timeline for Lapack 3.9 in MKL :)

**Comment by oleksandr-pavlyk** [comment]
@h-vetinari Per [what's new in Lapack 3.9.0](http://www.netlib.org/lapack/lapack-3.9.0.html), it is supported in MKL 2020.0.4:

```
In [2]: mkl_rt = ctypes.cdll.LoadLibrary("libmkl_rt.so")

In [3]: [hasattr(mkl_rt, fname) for fname in ['dgesvdq', 'sgesvdq', 'dorhr_col', 'sorhr_col', 'dorgtsqr', 'sorgtsqr']]
Out[3]: [True, True, True, True, True, True]

In [4]: import mkl

In [5]: mkl.get_version_string()
Out[5]: 'Intel(R) Math Kernel Library Version 2020.0.4 Product Build 20200917 for Intel(R) 64 architecture applications'
```

**Comment by h-vetinari** [comment]
@oleksandr-pavlyk 

Thanks for the update. I'm trying to build for this in https://github.com/conda-forge/blas-feedstock/pull/55. Since this feedstock already has 2020.4, I'm closing the issue here.
